import type { Bucket, Factor } from "./types";

/**
 * Default bucket weights — match the user's scoring spec.
 */
export const DEFAULT_BUCKETS: Bucket[] = [
  {
    id: "apartment",
    name: "Apartment",
    description: "How good is the apartment itself? Unit, building, amenities.",
    weight: 40,
  },
  {
    id: "location",
    name: "Location",
    description: "Is this a good place to live day-to-day? Neighborhood, commute, risks.",
    weight: 35,
  },
  {
    id: "financial",
    name: "Financial",
    description: "Is this apartment worth the money?",
    weight: 25,
  },
];

/**
 * Default factors organized by the spec's three buckets.
 *
 * Weight values are taken directly from the spec's "Suggested Weight Within Bucket"
 * column. They don't need to sum to exactly 100 — the scoring engine normalizes
 * by the sum of weights within each bucket.
 */
export const DEFAULT_FACTORS: Factor[] = [
  // ── Apartment bucket ──────────────────────────────────────────────────────
  {
    id: "f-sqft",
    bucketId: "apartment",
    name: "Square footage",
    description: "Total interior size of the unit.",
    type: "numeric",
    weight: 12,
    min: 400,
    max: 1500,
    direction: "higher",
    unit: "sqft",
  },
  {
    id: "f-layout",
    bucketId: "apartment",
    name: "Layout quality",
    description: "Is the floor plan efficient? Are rooms well proportioned and connected?",
    type: "rating",
    weight: 12,
  },
  {
    id: "f-natural-light",
    bucketId: "apartment",
    name: "Natural light",
    description: "How bright is the unit on a typical day?",
    type: "rating",
    weight: 8,
  },
  {
    id: "f-laundry",
    bucketId: "apartment",
    name: "In-unit laundry",
    type: "boolean",
    weight: 10,
  },
  {
    id: "f-hvac",
    bucketId: "apartment",
    name: "Central AC / heating quality",
    description: "Is the climate control modern and effective?",
    type: "rating",
    weight: 8,
  },
  {
    id: "f-storage",
    bucketId: "apartment",
    name: "Storage / closet space",
    type: "rating",
    weight: 5,
  },
  {
    id: "f-balcony",
    bucketId: "apartment",
    name: "Balcony / outdoor space",
    type: "boolean",
    weight: 4,
  },
  {
    id: "f-parking",
    bucketId: "apartment",
    name: "Parking available",
    type: "boolean",
    weight: 8,
  },
  {
    id: "f-ev",
    bucketId: "apartment",
    name: "EV charging",
    type: "boolean",
    weight: 4,
  },
  {
    id: "f-gym",
    bucketId: "apartment",
    name: "Gym / fitness amenities",
    type: "boolean",
    weight: 3,
  },
  {
    id: "f-pool",
    bucketId: "apartment",
    name: "Pool / clubhouse / coworking",
    type: "boolean",
    weight: 3,
  },
  {
    id: "f-overall",
    bucketId: "apartment",
    name: "Apartment overall feeling",
    description: "Gut check after the tour — does this place feel right?",
    type: "rating",
    weight: 6,
  },

  // ── Location bucket ───────────────────────────────────────────────────────
  {
    id: "f-safety",
    bucketId: "location",
    name: "Safety / crime perception",
    description: "How safe does the area feel? Higher = safer.",
    type: "rating",
    weight: 18,
  },
  {
    id: "f-walkability",
    bucketId: "location",
    name: "Walkability",
    description: "Can you reach daily needs on foot? Higher = more walkable.",
    type: "rating",
    weight: 10,
  },
  {
    id: "f-amenities",
    bucketId: "location",
    name: "Restaurants, coffee, groceries",
    description: "Variety and quality within walking distance.",
    type: "rating",
    weight: 8,
  },
  {
    id: "f-vibe",
    bucketId: "location",
    name: "Neighborhood vibe",
    description: "Overall feel — character, energy, quality of life.",
    type: "rating",
    weight: 12,
  },
  {
    id: "f-distance-downtown",
    bucketId: "location",
    name: "Distance to downtown LA",
    type: "numeric",
    weight: 8,
    min: 0,
    max: 30,
    direction: "lower",
    unit: "mi",
  },
  {
    id: "f-freeway",
    bucketId: "location",
    name: "Freeway / major road access",
    description: "How easy is it to jump on a freeway when you need to drive?",
    type: "rating",
    weight: 7,
  },
  {
    id: "f-commute",
    bucketId: "location",
    name: "Commute to work",
    description: "Door-to-desk, in minutes.",
    type: "numeric",
    weight: 10,
    min: 5,
    max: 60,
    direction: "lower",
    unit: "min",
  },
  {
    id: "f-traffic",
    bucketId: "location",
    name: "Traffic pain level",
    description: "How bad is local traffic? Higher = less pain.",
    type: "rating",
    weight: 7,
  },
  {
    id: "f-lax",
    bucketId: "location",
    name: "Proximity to LAX",
    description: "Distance in miles. Direction depends on whether you want to be close (travel) or far (noise).",
    type: "numeric",
    weight: 5,
    min: 0,
    max: 30,
    direction: "lower",
    unit: "mi",
  },
  {
    id: "f-livability",
    bucketId: "location",
    name: "Livability Score (AreaVibes)",
    description: "Pulled from AreaVibes.com. Out of 100.",
    type: "numeric",
    weight: 5,
    min: 0,
    max: 100,
    direction: "higher",
  },
  {
    id: "f-parks",
    bucketId: "location",
    name: "Parks / nature access",
    type: "rating",
    weight: 4,
  },
  // Risk fields — still part of the Location bucket. Higher score = LOWER concern.
  {
    id: "f-wildfire",
    bucketId: "location",
    name: "Wildfire risk",
    description: "Higher score = lower concern. (10 = very low risk, 1 = very high risk.)",
    type: "rating",
    weight: 5,
  },
  {
    id: "f-earthquake",
    bucketId: "location",
    name: "Earthquake / building concern",
    description: "Higher score = lower concern.",
    type: "rating",
    weight: 4,
  },
  {
    id: "f-disorder",
    bucketId: "location",
    name: "Homelessness / street disorder",
    description: "Higher score = less concern in the immediate area.",
    type: "rating",
    weight: 5,
  },
  {
    id: "f-noise",
    bucketId: "location",
    name: "Noise from roads / nightlife",
    description: "Higher score = quieter.",
    type: "rating",
    weight: 5,
  },

  // ── Financial bucket ──────────────────────────────────────────────────────
  {
    id: "f-rent-vs-budget",
    bucketId: "financial",
    name: "Monthly rent vs target budget",
    description: "Base rent compared to your target. Uses the step function from the spec.",
    type: "rent_vs_budget",
    weight: 25,
    costMode: "rent",
  },
  {
    id: "f-true-cost",
    bucketId: "financial",
    name: "True monthly cost",
    description: "Rent + parking + utilities + pet fees + required fees, vs your target budget.",
    type: "rent_vs_budget",
    weight: 25,
    costMode: "true_cost",
  },
  {
    id: "f-upfront",
    bucketId: "financial",
    name: "Upfront cost",
    description: "First month + last + security deposit + admin fees.",
    type: "numeric",
    weight: 10,
    min: 1000,
    max: 15000,
    direction: "lower",
    unit: "$",
  },
  {
    id: "f-utilities",
    bucketId: "financial",
    name: "Utilities estimate",
    description: "Average monthly utilities — electric, gas, water, internet.",
    type: "numeric",
    weight: 8,
    min: 50,
    max: 500,
    direction: "lower",
    unit: "$",
  },
  {
    id: "f-parking-cost",
    bucketId: "financial",
    name: "Parking cost",
    description: "Monthly cost of a parking space, if any.",
    type: "numeric",
    weight: 8,
    min: 0,
    max: 400,
    direction: "lower",
    unit: "$",
  },
  {
    id: "f-concessions",
    bucketId: "financial",
    name: "Rent concessions / specials",
    description: "How attractive are the move-in specials? 10 = great deal.",
    type: "rating",
    weight: 7,
  },
  {
    id: "f-lease-flex",
    bucketId: "financial",
    name: "Lease flexibility",
    description: "Term length options, sublet/transfer policies, break fees.",
    type: "rating",
    weight: 3,
  },
];

/** The default target monthly budget — used by `rent_vs_budget` factors. */
export const DEFAULT_TARGET_BUDGET = 3100;
