import type { Factor } from "./types";

/** A starter set of factors. Users can edit, remove, or add their own in Settings. */
export const DEFAULT_FACTORS: Factor[] = [
  {
    id: "f-price",
    name: "Price",
    description: "Monthly rent (or price).",
    type: "number",
    weight: 5,
    direction: "lower",
    min: 1000,
    max: 6000,
    unit: "$",
  },
  {
    id: "f-sqft",
    name: "Sqft",
    description: "Total square footage.",
    type: "number",
    weight: 3,
    direction: "higher",
    min: 400,
    max: 1500,
    unit: "sqft",
  },
  {
    id: "f-commute",
    name: "Commute",
    description: "Door-to-desk commute, in minutes.",
    type: "number",
    weight: 4,
    direction: "lower",
    min: 5,
    max: 60,
    unit: "min",
  },
  {
    id: "f-natural-light",
    name: "Natural light",
    description: "How bright is the unit on a typical day?",
    type: "rating",
    weight: 3,
    direction: "higher",
    min: 1,
    max: 10,
  },
  {
    id: "f-noise",
    name: "Noise",
    description: "How noisy is it (street, neighbors, mechanical)?",
    type: "rating",
    weight: 3,
    direction: "lower",
    min: 1,
    max: 10,
  },
  {
    id: "f-neighborhood",
    name: "Neighborhood vibe",
    description: "Walkability, restaurants, parks, safety.",
    type: "rating",
    weight: 4,
    direction: "higher",
    min: 1,
    max: 10,
  },
  {
    id: "f-condition",
    name: "Condition",
    description: "Overall condition / age / finishes.",
    type: "rating",
    weight: 3,
    direction: "higher",
    min: 1,
    max: 10,
  },
  {
    id: "f-laundry",
    name: "In-unit laundry",
    type: "boolean",
    weight: 2,
    direction: "higher",
  },
  {
    id: "f-dishwasher",
    name: "Dishwasher",
    type: "boolean",
    weight: 1,
    direction: "higher",
  },
  {
    id: "f-pet-friendly",
    name: "Pet friendly",
    type: "boolean",
    weight: 1,
    direction: "higher",
  },
];
